openapi: 3.0.3
info:
  title: Account Management Service
  description: Microservice for bank account management
  version: 1.0.0
servers:
  - url: http://localhost:8085
paths:
  /account:
    post:
      tags:
        - account
      summary: Create a bank account
      description: Create a bank account
      operationId: createAccount
      requestBody:
        description: Account created object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreate'
        required: true
      responses:
        '201':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Error in input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
    get:
      tags:
        - account
      summary: Get list of bank accounts
      description: Get list of bank accounts
      operationId: accountsList
      responses:
        '200':
          description: List of successfully retrieved accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '500':
          description: Error getting accounts
  /account/{id}:
    get:
      tags:
        - account
      summary: Get account details by its ID
      description: Get details of a account by their ID
      operationId: getAccountsById
      parameters:
        - name: id
          in: path
          description: 'Unique account identifier'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account information successfully obtained
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - account
      summary: Delete a bank account
      description: ''
      operationId: deleteAccount
      parameters:
        - name: id
          in: path
          description: The account that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Account deleted successfully
        '400':
          description: Invalid id supplied
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /account/{accountId}/deposit:
    put:
      tags:
        - account
      summary: Make a deposit into a bank account
      description: ''
      operationId: depositIntoAccount
      parameters:
        - name: accountId
          in: path
          description: Account that increases its balance with the deposit
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: Amount to deposit
      responses:
        '200':
          description: Deposit made successfully
          content:
            applicaation/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Error in input data
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /account/{accountId}/withdraw:
    put:
      tags:
        - account
      summary: Make a withdrawal from a bank account
      description: ''
      operationId: withdrawFromAccount
      parameters:
        - name: accountId
          in: path
          description: Account that decreases its balance with withdrawal
          required: true
          schema:
            type: string
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: Amount to withdraw
      responses:
        '200':
          description: Withdraw made successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Error in input data
        '404':
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Account:
      type: object
      required:
       - accountNumber
       - balance
       - accountType
       - customerId
      properties:
        id:
          type: string
          example: 1
          description: Unique identifier of the account in the database
        accountId:
          type: string
          description: Account identifier in the client context
        accountNumber:
          type: string
          example: '1234-5678-9098-7654'
        balance:
          type: number
          format: double
          default: 0.0
          description: Current account balance
        accountType:
          type: string
          enum: [AHORROS, CORRIENTE]
          example: AHORROS
          description: type of bank account
        customerId:
          type: string
          description: Customer ID of the account owner
    AccountCreate:
      type: object
      required:
        - accountType
        - customerId
      properties:
        accountType:
          type: string
          enum: [AHORROS, CORRIENTE]
          description: Type of bank account to create
        customerId:
          type: string
          description: Customer ID to associate the account with
    Error:
      type: object
      properties:
        code:
          type: integer
          example: 400
        message:
          type: string
          example: 'Validation failed'